In [1]:
# list
list1 = [1,2,3,4,5]
print(list1)
print(type(list1))

[1, 2, 3, 4, 5]
<class 'list'>


In [4]:
import numpy as np

In [5]:
np_array = np.array([1,2,3,4,5])
print(np_array)
print(type(np_array))

[1 2 3 4 5]
<class 'numpy.ndarray'>


In [6]:
# creating a 1 dim array
a = np.array([1,2,3,4])
print(a)
print(a.shape)

b = np.array([(1,2,3,4),(5,6,7,8)])
print(b)
print(b.shape)

c = np.array([(1,2,3,4),(5,6,7,8)], dtype= float)
print(c)
print(c.shape)

[1 2 3 4]
(4,)
[[1 2 3 4]
 [5 6 7 8]]
(2, 4)
[[1. 2. 3. 4.]
 [5. 6. 7. 8.]]
(2, 4)


In [7]:
# inital placeholders in numpy arrays

In [12]:
# create an numpy array of zeros
x = np.zeros((4,5))
print(x)

[[0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0.]]


In [13]:
# create an numpy array of ones
y = np.ones((3,3))
print(y)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [14]:
# create an array of a particular value
z = np.full((5,4),5)
print(z)

[[5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]
 [5 5 5 5]]


In [15]:
# create an identity matrix
a = np.eye(4)
print(a)

[[1. 0. 0. 0.]
 [0. 1. 0. 0.]
 [0. 0. 1. 0.]
 [0. 0. 0. 1.]]


In [16]:
# create an numpy array with random value
b = np.random.random((3,4))
print(b)

[[0.42826709 0.32356181 0.68667602 0.80625551]
 [0.00667435 0.49435587 0.52375816 0.74054036]
 [0.42072789 0.68506403 0.53359868 0.03094072]]


In [17]:
# create an numpy with random integer values array within a specific range
c = np.random.randint(10,100,(3,5))
print(c)

[[84 47 80 13 87]
 [73 59 36 12 55]
 [34 51 70 74 46]]


In [18]:
# array of evenly spaced values
d = np.linspace(10,30,5)
print(d)
# specifying the number of values required

[10. 15. 20. 25. 30.]


In [19]:
# array of evenly spaced values --> specifying the step
e = np.arange(10,30,5)
print(e)

[10 15 20 25]


In [20]:
# convert a list to a numpy array
list2 = [10,20,20,20,50]
np_array = np.array(list2)
print(np_array)
print(type(np_array))

[10 20 20 20 50]
<class 'numpy.ndarray'>


In [21]:
# analysing a numpy array

In [22]:
c = np.random.randint(10,90,(5,5))
print(c)

[[54 21 32 44 78]
 [18 46 77 51 38]
 [41 57 28 76 75]
 [86 73 56 41 27]
 [12 12 11 25 13]]


In [23]:
# array dimension
print(c.shape)

# number of dimension
print(c.ndim)

#number of elements in an array
print(c.size)

# checking the datatype of values in the array
print(c.dtype)

(5, 5)
2
25
int32


In [24]:
# Mathematical operations on an numpy array

In [26]:
list1 = [1,2,3,4,5]
list2 = [6,7,8,9,10]
print(list1+list2)      # concatenate or joins two list

[1, 2, 3, 4, 5, 6, 7, 8, 9, 10]


In [28]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[2 9 7]
 [2 7 2]
 [7 4 0]]
[[12 15 17]
 [18 12 14]
 [14 19 11]]


In [30]:
print(a+b)
print(a-b)
print(a*b)
print(a/b)

[[14 24 24]
 [20 19 16]
 [21 23 11]]
[[-10  -6 -10]
 [-16  -5 -12]
 [ -7 -15 -11]]
[[ 24 135 119]
 [ 36  84  28]
 [ 98  76   0]]
[[0.16666667 0.6        0.41176471]
 [0.11111111 0.58333333 0.14285714]
 [0.5        0.21052632 0.        ]]


In [31]:
a = np.random.randint(0,10,(3,3))
b = np.random.randint(10,20,(3,3))
print(a)
print(b)

[[5 5 3]
 [8 8 5]
 [1 0 3]]
[[18 18 19]
 [12 13 13]
 [18 17 18]]


In [32]:
print(np.add(a,b))
print(np.subtract(a,b))
print(np.multiply(a,b))
print(np.divide(a,b))

[[23 23 22]
 [20 21 18]
 [19 17 21]]
[[-13 -13 -16]
 [ -4  -5  -8]
 [-17 -17 -15]]
[[ 90  90  57]
 [ 96 104  65]
 [ 18   0  54]]
[[0.27777778 0.27777778 0.15789474]
 [0.66666667 0.61538462 0.38461538]
 [0.05555556 0.         0.16666667]]


In [33]:
# array manipulation

In [34]:
array = np.random.randint(0,10,(2,3))
print(array)
print(array.shape)

[[4 9 3]
 [3 9 2]]
(2, 3)


In [35]:
# transpose
trans = np.transpose(array)
print(trans)
print(trans.shape)

[[4 3]
 [9 9]
 [3 2]]
(3, 2)


In [36]:
# another way of transpose
trans2 = array.T
print(trans2)
print(trans2.shape)

[[4 3]
 [9 9]
 [3 2]]
(3, 2)


In [ ]:
# reshaping the array
a = np.random.randint(0,10,(2,3))
print(a)
print(a.shape)

b = a.reshape(3,2)
print(b)
